<div id='page_title_div' style='text-align:center;'><h2 style='margin:0px !important'>{{@page_title}}</h2></div>
<div id='form_div' style='clear:both;margin-left:40px;margin-right:10px;background-color:#DDDDDD;'>{{@form}}</div>
<div id='report_results' style='height: 90%; width: 100%;'></div>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.0.min.js"></script>
<!--[if lte IE 8]><script language="javascript" type="text/javascript" src="excanvas.min.js"></script><![endif]-->
<script type="text/javascript" src="/assets/js/flot/jquery.flot.js"></script>
<script type="text/javascript" src="/assets/js/flot/jquery.flot.resize.js"></script>
<script type='application/x-javascript'>
  <?php //TODO: Update this to allow multiple graphs to be added ?>
  var report_div = $('#report_results');
  var report_results = {{@report_results}};
  $(document).ready(function() { 
  	var report_plot = $.plot(report_div, report_results); 
  	report_div.resize();
  });
</script>