<div style='text-align:center;'><h2>{{@page_title}}</h2></div><br/>
<div id='report_results' style='height: 90%; width: 100%;'></div>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="/assets/js/highcharts/highcharts.js"></script>
<script type='application/x-javascript'>
  $(document).ready(function() { var chart = new Highcharts.Chart(
    {{@content}}
  ); });
</script>
