<div id='page_title_div' style='text-align:center;'><h2 style='margin:0px !important'>{{@page_title}}</h2></div>
<div id='form_div' style='clear:both;margin-left:40px;margin-right:10px;background-color:#DDDDDD;'>{{@form}}</div>
<div id='report_results' style='height: 85%; width: 100%;'></div>
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.8.0.min.js"></script>
<script type="text/javascript" src="/assets/js/highcharts/highcharts.js"></script>
<script type="text/javascript" src="/assets/js/jQuery.unserializeForm.js"></script>
<script type="text/javascript" src="/assets/js/squerly.js"></script>
<script type='application/x-javascript'>
  $(document).ready(function() { var chart = new Highcharts.Chart(
    {{@report_results}}
  ); });
</script>
