<div id='page_title_div'><h2>{{@page_title}}</h2></div>
<div id='expand_form_div' onclick="$('#form_div').toggle();">[+/-] Show/Hide Options</div><br/>
<div id='form_div' style='display: none;'>{{@form}}{{@navigation}}</div>
<div id='report_results'></div>

<!-- JS -->
<script type="text/javascript" src="http://ajax.aspnetcdn.com/ajax/jQuery/jquery-1.9.1.min.js"></script>
<script type="text/javascript" src="/assets/js/highcharts/highcharts.js"></script>
<script type="text/javascript" src="/assets/js/jQuery.unserializeForm.js"></script>
<script type="text/javascript" src="/assets/js/squerly.js"></script>

<!-- CSS -->
<link rel="stylesheet" type="text/css" href="/assets/css/squerly.css" />

<script type='application/x-javascript'>
  $(document).ready(function() { var chart = new Highcharts.Chart(
    {{@report_results}}
  ); });
</script>
